### ISSUE TITLE
Should we remove fastboot binaries?

### ISSUE THREAD

**Issue by juliandescottes** [mozilla-extensions/devtools-adb-extension#1]
The fastboot files are no longer listed in [adb.json](https://github.com/mozilla/devtools-adb-extension/blob/master/adb.json). Should they be removed from this repository?

I can't see any code to support fastboot in https://bugzilla.mozilla.org/show_bug.cgi?id=1469054 so I assume we are removing the support for this feature?

**Comment by juliandescottes** [comment]
Had a quick chat with @hiikezoe who said it should be ok to remove them.

@jryans do you confirm?

**Comment by jryans** [comment]
Right, it was only used for Firefox OS.

**Comment by juliandescottes** [comment]
thanks :+1:
