### ISSUE TITLE
Rename extension to "ADB Extension"

### ISSUE THREAD

**Issue by juliandescottes** [mozilla-extensions/devtools-adb-extension#10]
Right now the repository name is "devtools-adb-extension", but the extension's name "ADB binary provider". For consistency I would like to rename the extension to "ADB Extension" or "DevTools ADB Extension". 

Ultimately this extension might be hidden from about:addons (once we have a satisfying way to add/remove the extension from DevTools UI). But it would still be nice to agree on the name.

@hiikezoe @birtles objections, suggestions?

**Comment by birtles** [comment]
Either sounds fine to me. "ADB wrapper" makes most sense to me, but it's not a very nice name I guess. Hiro has a better idea of what it does.

**Comment by hiikezoe** [comment]
I don't have any better idea.  And no objections for either 'ADB Extension' or 'DevTools ADB Extension'.

**Comment by juliandescottes** [comment]
![image](https://user-images.githubusercontent.com/1141550/45737552-712a2c80-bbee-11e8-906d-11fbf1a20b98.png)

We could have a fun icon for ADB wrapper :)
