### ISSUE TITLE
DevTools ADB Extension forces itself to be allowed in private windows (won't let you disallow it)

### ISSUE THREAD

**Issue by dholbert** [mozilla-extensions/devtools-adb-extension#17]
STR:
 1. Install Firefox DevTools ADB Extension in Firefox Nightly (by visiting Tools | Web Developer | WebIDE -- this causes the extension to suddenly appear in your list of installed addons).

 2. In a new tab, visit about:addons and click "extensions"
 --> Note that Firefox DevTools ADB Extension is tagged as `ALLOWED IN PRIVATE WINDOWS`

 3. Click the addon to view its settings, and try to click radio button labeled...
      "Run in Private Windows: ... [] Don't allow"

EXPECTED RESULTS: Click should be honored, "Don't Allow" should be selected.
ACTUAL RESULTS: "Don't Allow" is only selected very briefly, and then "Allow" becomes selected again.

There doesn't seem to be any way to select "Don't Allow".  You can get it selected for slightly longer if you Disable the addon and then pick Don't Allow while it's disabled, but once you reenable it, then "Allow" becomes selected on your next (re)-load of about:addons.

**Comment by dholbert** [comment]
Screencast of bug: https://www.dropbox.com/s/dgvb60jlmzg6ag6/devtools-adb-extension.ogv?dl=0

I'm using Firefox Nightly 68.0a1 (2019-03-21) (64-bit)

**Comment by juliandescottes** [comment]
Thanks for logging!

I don't see anything in the extension's manifest that would lead to this issue.
https://github.com/mozilla/devtools-adb-extension/blob/master/extension/template-manifest.json
And we don't have any script.

I couldn't see any obvious error when trying to click the radio. 
If I download the XPI and install it as a temporary addon, then the radio works fine.

I will open a bug on Bugzilla to get help from addons team.

**Comment by juliandescottes** [comment]
Closing, will be fixed by per https://bugzilla.mozilla.org/show_bug.cgi?id=1533150

**Comment by dholbert** [comment]
Sorry, I should have noted that I also filed this as https://bugzilla.mozilla.org/show_bug.cgi?id=1538025 .  Happily, it seems both bugs were duped to a place where a fix was just landed. :)
