### ISSUE TITLE
Migrate template-manifest.json from "applications" to "browser_specific_settings"

### ISSUE THREAD

**Issue by rpl** [mozilla-extensions/devtools-adb-extension#27]
I noticed this as part of reviewing https://phabricator.services.mozilla.com/D160057 (part of [Bug 1797050](https://bugzilla.mozilla.org/show_bug.cgi?id=1797050)) and so I thought to file this followup upfront: 

In MV3 we plan to fully deprecate "applications" from the manifest.json, in favor from the other alias "browser_specific_settings" (which we support from quite a long time and so it should be backward compatible enough also with older Firefox versions) and so we may change the template-manifest.json part of this repo to make sure we migrated the adb addon away from it ahead to its future deprecation.

The diff to apply the change describe above would look like in the following diff:
```diff
diff --git a/extension/template-manifest.json b/extension/template-manifest.json
index 8888843..f0a47ab 100644
--- a/extension/template-manifest.json
+++ b/extension/template-manifest.json
@@ -4,7 +4,7 @@
   "author": "Mozilla & Android Open Source Project",
   "version": "@@VERSION@@",
   "description": "An extension providing ADB binaries for Android remote debugging in Firefox DevTools. May be automatically installed when using about:debugging.",
-  "applications": {
+  "browser_specific_settings": {
     "gecko": {
       "id": "adb@mozilla.org",
       "strict_min_version": "64.0a1",
```

**NOTE:** the template-updates.json file also includes an "applications" property which **SHOULD NOT** be changed to "browser_specific_settings", for that one Firefox doesn't yet support any alias named "browser_specific_settings" and unfortunately its named and its format looks basically the same as the manifest.json one which may be confusing and so I'm calling it out explicitly in this issue to make sure we don't mistakenly change that one along with the manifest.json one.

**Comment by juliandescottes** [comment]
Thanks for filing @rpl ! Do you know we can expect `applications` to be fully deprecated. Just to know how urgent it is for us to release an updated version of the extension

**Comment by willdurand** [comment]
@juliandescottes `applications` won't work in MV3, in MV2 it will likely be still allowed. It isn't urgent I think.

**Comment by willdurand** [comment]
see #33
